version: "3.7"

services:
  vscode:
    image: basedevcontainer:latest
    volumes:
      - ../:/workspace
      - ~/.ssh:/home/developer/.ssh:z
      # Shell history persistence
      - ~/.zsh_history:/home/developer/.zsh_history:z
      # Git config
      - ~/.gitconfig:/home/developer/.gitconfig:z
    environment:
      - TZ=
    entrypoint: ["zsh", "-c", "while sleep 1000; do :; done"]
